src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Booking duration in minutes.</description>
        <label>Duration</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Artist__c</fullName>
        <description>Name of artist that originally released this song.</description>
        <inlineHelpText>Name of artist that originally released this song.</inlineHelpText>
        <label>Original Artist</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seconds__c</fullName>
        <label>Seconds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Proposed</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CoverSongTestDataCreator.cls
@IsTest
public class CoverSongTestDataCreator {

    public static void insertSongs(Integer songCount){
        List<Song__c> songs = new List<Song__c>();
        for(Integer i = 0; i < songCount; i++){
            Song__c s = new Song__c();
            s.Name = 'Song ' + i;
            s.Rating__c = String.valueOf(Math.Round(Math.Random()*4+1));
            s.Minutes__c = Math.Round(Math.Random()*4+1);
            s.Seconds__c = Math.Round(Math.Random()*59);
            s.Status__c = CoverSongConstants.SongStatus_Active;
            s.Original_Artist__c = 'Artist ' + i;
            songs.add(s);
        }
        insert songs;
    }
    
    public static Id insertVenue(){
        Venue__c v = new Venue__c();
        v.Name = 'Test Venue';
        insert v;
        return v.Id;
    }
    
    //Insert songs before calling me.
    //Not inserting as a part of this method, as we want bookings to leverage the same lists of songs.
    public static Id insertFullBooking(){
        Id venueId = insertVenue();
        Booking__c b = new Booking__c();
        b.Name = 'Test Booking';
        b.Date__c = DateTime.now();
        b.Duration__c = 60;
        b.Venue__c = venueId;

        insert b;
        return b.Id;
    }
}