src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Playlist__c.object
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SongToPlaylist__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>SongToPlaylist</label>
    <nameField>
        <label>SongToPlaylist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SongsToPlaylists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BookingHelper_Test.cls
@IsTest
public class BookingHelper_Test {

    private static testMethod void testCreateBooking(){
        //TODO : Leverage System.runAs with the profile band managers will ultimately use.
        
        //Insert Songs
        CoverSongTestDataCreator.insertSongs(50);
        
        //Insert other bookings outside the one we're going to test.  This could be converted into a single method call in the test data creator.
        CoverSongTestDataCreator.insertFullBooking();
        CoverSongTestDataCreator.insertFullBooking();
        CoverSongTestDataCreator.insertFullBooking();
        
        Test.startTest();
            Id bookingId = CoverBandTestDataCreator.insertFullBooking();
        Test.stopTest();
        
        //Get the playlist generated.
        Booking__c testBooking = [SELECT Playlist__c FROM Booking__c WHERE Id = :bookingId];
        
        //Assert a playlist was generated.
        System.assertNotEquals(null, testBooking.Playlist__c);
        
        List<SongToPlaylist__c> stp = [SELECT Song__c, Playlist__c FROM SongToPlaylist__c WHERE Playlist__c =: testBooking.Playlist__c];
        
        //Assert the playlist songs were generated
        System.assert(!stp.isEmpty());
        
    }
    
    //TODO : I'd probably add more tests here with exact playlists
    //to check for specific fits, what's in, what's out, etc.
}