src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Booking duration in minutes.</description>
        <label>Duration</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Playlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Playlist__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seconds__c</fullName>
        <label>Seconds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Proposed</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SongToPlaylist__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>SongToPlaylist</label>
    <nameField>
        <label>SongToPlaylist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SongsToPlaylists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BookingHelper.cls
public class BookingHelper {
    
    //For the purpose of this challenge, I'm going to assume there is only one booking scheduled at a time.
    public static void processBookings(List<Booking__c> bookings){
        if(!bookings.isEmpty()){
            handleBooking(bookings[0]);
        }
    }
    
    private static void handleBooking(Booking__c booking){
        //Get the valid songs for a booking.
        List<Song__c> songs = getSongs(booking.Date__c);
        //Get the duration of each song in seconds.
        Map<Id, Integer> durationMap = getDurations(songs);
        //Get the playlist songs
        Set<Id> playlistIds = getPlaylistIds(songs, (Integer)booking.Duration__c, durationMap);
        Id playlistId = PlaylistHelper.generatePlaylist(playlistIds, booking.Date__c);
        booking.Playlist__c = playlistId;
    }
    
    //Method is a bit long, could be broken up.
    private static List<Song__c> getSongs(DateTime bookingDate){
        
        //Vars we'll need for dates.
        Integer bookingMonth = bookingDate.month();
        Integer bookingYear = bookingDate.year();
        Date d = bookingDate.date();
        Date dateStart = d.toStartOfMonth();
        Date dateEnd = dateStart + Date.daysInMonth(bookingYear, bookingMonth);
        
        //Collections we'll need for processing.
        Set<Id> songBlacklist = new Set<Id>();
        Map<Id, Set<Id>> songCounts = new Map<Id, Set<Id>>();
        //Query junction object
        for(SongToPlaylist__c sp : [SELECT Id, Song__c FROM SongToPlaylist__c WHERE Playlist__r.Date__c >= : dateStart 
                                                                                                                 AND Playlist__r.Date__c <= : dateEnd 
                                                                                                                 AND Song__r.Status__c =: CoverSongConstants.SongStatus_Active]){
            if(!songCounts.containsKey(sp.Song__c)){
                songCounts.put(sp.Song__c, new Set<Id>());
            }    
            songCounts.get(sp.Song__c).add(sp.Id);
        }
        
        
        //Generate Blacklist
        for(Id i : songCounts.keySet()){
            Integer uses = songCounts.get(i).size();
            if(uses >= 3){
                songBlacklist.add(i);
            }
        }
        
        return [SELECT Id, Rating__c, Minutes__c, Seconds__c FROM Song__c WHERE Id NOT IN : songBlacklist AND Status__c =: CoverSongConstants.SongStatus_Active];
    }
    
    //Calculate the duration in seconds based on mins/secs
    //This should be a formula field, but the rules said...
    private static Map<Id, Integer> getDurations(List<Song__c> songs){
        Map<Id, Integer> durations = new Map<Id, Integer>();
        
        for(Song__c s : songs){
            Integer minutes = (Integer)s.Minutes__c;
            Integer seconds = (Integer)s.Seconds__c;
            
            durations.put(s.Id, Integer.valueOf(s.Seconds__c + (60 * s.Minutes__c)));
        }
        
        return durations;
    }
    
    //Taking a simple approach for this challenge only factoring low quality songs.
    //We might, in the future, consider ordering by quality, and always using those first - as well as more complex fitting logic.
    private static Set<Id> getPlaylistIds(List<Song__c> songs, Integer durationMinutes, Map<Id, Integer> durations){
        Set<Id> result = new Set<Id>();
        Integer durationSeconds = durationMinutes * 60;
        Integer playlistDuration = 0;
        Integer lowSongs = 0;
        
        for(Song__c s : songs){
            
            //Low Song Check
            if(Integer.valueOf(s.Rating__c) == 1){
                if(lowSongs >= 3){
                    continue;
                }
                lowSongs++;
            }    
            //Duration Check
            Integer thisDuration = durations.get(s.Id);
            if(thisDuration + playlistDuration <= durationSeconds){
                result.add(s.Id);
                playlistDuration += thisDuration;
            }   
            
            //TODO : Here, we could look at the songs that were skipped due to low quality.  Consider adding them if they fit in the duration.
            //For example, if we ran out of higher quality songs.
        }

        return result;
    }
}