src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Playlist__c.object
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Artist__c</fullName>
        <description>Name of artist that originally released this song.</description>
        <inlineHelpText>Name of artist that originally released this song.</inlineHelpText>
        <label>Original Artist</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seconds__c</fullName>
        <label>Seconds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SongToPlaylist__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>SongToPlaylist</label>
    <nameField>
        <label>SongToPlaylist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SongsToPlaylists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PlaylistViewController.cls
public class PlaylistViewController {

    @AuraEnabled
    public static List<Song__c> getPlaylist(Id bookingId){
        if(bookingId == null){
            return null;
        }
        List<Song__c> returnList = new List<Song__c>();
        List<Booking__c> bookings = [SELECT Id, Playlist__c FROM Booking__c WHERE Id = : bookingId LIMIT 1];
        
        if(!bookings.isEmpty()){
            for(SongToPlaylist__c stp : [SELECT Song__r.Name, Song__r.Minutes__c, Song__r.Seconds__c, Song__r.Original_Artist__c FROM SongToPlaylist__c WHERE Playlist__c = : bookings[0].Playlist__c]){
                returnList.add(stp.Song__r);
            }   
        }
        return returnList;
    }
}