src/objects/Playlist__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SongToPlaylist__c.object
<CustomObject>
    <fields>
        <fullName>Playlist__c</fullName>
        <label>Playlist</label>
        <referenceTo>Playlist__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>SongsToPlaylists</relationshipLabel>
        <relationshipName>SongsToPlaylists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>SongToPlaylist</label>
    <nameField>
        <label>SongToPlaylist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SongsToPlaylists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PlaylistHelper.cls
public class PlaylistHelper {

    public static Id generatePlaylist(Set<Id> songIds, DateTime thisDate){
        Playlist__c p = new Playlist__c();
        p.Date__c = thisDate;
        insert p;
        
        List<SongToPlaylist__c> songs = new List<SongToPlaylist__c>();
        for(Id i : songIds){
            SongToPlaylist__c stp = new SongToPlaylist__c();
            stp.Song__c = i;
            stp.Playlist__c = p.Id;
            songs.add(stp);
        }
        insert songs;
        
        return p.Id;
    }
}