src/objects/Song__c.object
<CustomObject>
    <description>Represents a cover song from our magnificent repertoire.</description>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Artist__c</fullName>
        <description>Name of artist that originally released this song.</description>
        <inlineHelpText>Name of artist that originally released this song.</inlineHelpText>
        <label>Original Artist</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seconds__c</fullName>
        <label>Seconds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Proposed</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailToSongSuggestion.cls
global class EmailToSongSuggestion implements Messaging.InboundEmailHandler {
 
  global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, 
                                                       Messaging.InboundEnvelope env){
 
    Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
  
    String songName, songArtist, songDuration;
    String subject = email.subject;
    
    //Is this subject valid?
    if(String.isBlank(subject)){
        return null;
    }
    
    List<String> songParts = subject.split(',');
    //Have all its parts?  If you're suggesting a song, send me all the info!
    if(songParts.size() != 3){
        return null;
    }
    songName = songParts[0];
    songArtist = songParts[1];
    songDuration = songParts[2].trim();
    
    Map<String, Integer> durationParts = calculateDuration(songDuration);
    if(durationParts == null){
        return null;
    }
    
   
    Song__c song = new Song__c();
    song.Status__c = CoverSongConstants.SongStatus_Proposed;
    song.Name = songName;
    song.Original_Artist__c = songArtist;
    if(durationParts.containsKey('mins') && durationParts.containsKey('secs')){
        song.Minutes__c = durationParts.get('mins');
        song.Seconds__c = durationParts.get('secs');
    }
   
    try {
        insert song;
    }
   catch (QueryException e) {
       System.debug('Song insert went sideways: ' + e);
   }
   
   result.success = true;
   return result;
  }
  
  private Map<String, Integer> calculateDuration(String duration){
      if(String.isBlank(duration)){
          return null;
      }
      List<String> durationParts = duration.split(':');
      if(durationParts.size() != 2){
          return null;
      }
      Map<String, Integer> returnMap = new Map<String, Integer>();
      returnMap.put('mins', Integer.valueOf(durationParts[0]));
      returnMap.put('secs', Integer.valueOf(durationParts[1]));
      return returnMap;
  }
}